{% set name = "statmorph" %}
{% set version = "0.3.0" %}
{% set sha256 = "6b60fcffb07587797d76689d54c3e6bc2f9faa61c0a3921d93a268535971d48e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - scipy >=0.19
    - scikit-image >=0.14
    - astropy >=2.0
    - photutils >=0.3

test:
  imports:
    - statmorph

about:
  home: https://github.com/vrodgom/statmorph
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Non-parametric morphological diagnostics of galaxy images'
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: http://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
