{% set name = "statmorph" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30ad1e9ff1e69ac4223f5f289f9ad1f837a025a51e90c0d8d711f5ef6ace9ab0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.14.0
    - scipy >=0.19
    - scikit-image >=0.25.2
    - astropy >=2.0
    - photutils >=2.0

test:
  imports:
    - statmorph
    - statmorph.tests
  requires:
    - pytest

about:
  home: https://statmorph.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Non-parametric morphological diagnostics of galaxy images
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: https://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
