{% set name = "statmorph" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7aac9da469e97a0fc1b29d03a1c138ebe2ecb3be13432c7847fb15ea47c5d30

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.14.0
    - scipy >=0.19
    - scikit-image >=0.14
    - astropy >=2.0
    - photutils >=0.7

test:
  imports:
    - statmorph
    - statmorph.tests
  commands:
    - python -c "import statmorph.tests; statmorph.tests.runall()"

about:
  home: https://statmorph.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Non-parametric morphological diagnostics of galaxy images'
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: https://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
