{% set name = "statmorph" %}
{% set version = "0.3.3" %}
{% set sha256 = "ede396de1c9384b0b3a11d21187d370a6f0cc47f0e1f8803cb9a48f281095446" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - scipy >=0.19
    - scikit-image >=0.14
    - astropy >=2.0
    - photutils >=0.5

test:
  imports:
    - statmorph
  commands:
    - python -c "import statmorph.tests; statmorph.tests.runall()"

about:
  home: https://statmorph.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Non-parametric morphological diagnostics of galaxy images'
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: https://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
