{% set name = "statmorph" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c166f8b5f9faf168b6b4e733e5163aa5652ab94b3806e6d4cf6b74d71e62b1b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.14.0
    - scipy >=0.19
    - scikit-image >=0.14
    - astropy >=2.0
    - photutils >=0.7

test:
  imports:
    - statmorph
    - statmorph.tests
  requires:
    - pytest

about:
  home: https://statmorph.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Non-parametric morphological diagnostics of galaxy images
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: https://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
