{% set name = "statmorph" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 438526ba53fd7ae0bd0f5993f838987923d328649c214a0d63912d56e38a0f4e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.14.0
    - scipy >=0.19
    - scikit-image >=0.14
    - astropy >=2.0
    - photutils >=0.7

test:
  imports:
    - statmorph
    - statmorph.tests
  requires:
    - pytest

about:
  home: https://statmorph.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Non-parametric morphological diagnostics of galaxy images
  description: |
    Python code for calculating non-parametric morphological diagnostics
    of galaxy images.
  doc_url: https://statmorph.readthedocs.io/
  dev_url: https://github.com/vrodgom/statmorph

extra:
  recipe-maintainers:
    - vrodgom
