travis:
  secure:
    BINSTAR_TOKEN: oP5ZgPMteLRZP1608x2xNFf2LsZf8DXXdwEtBaPiv90CtsW8dIiOruFnUcRjaE/VqZTZlNkoBVZ/zbqVc8E+EdKBVqvEaSRwUv03UFWeSw4hZD4oEvyV9p416TTf0/IZVnibzoyojI/cFUv7FnhnQlKnwaU4QhdCTJtTQY1mqxABDd+IWz8Clz3Pj2fxtvZw739O+ZFNy2xlze1d+U6aWc7xciqe3uiVRKOgQOrdnEnOV1fFgulpWRJ98HoeOUbjDZRKJFFsfZJEbz7GkGZtIhvwqlJ976qkh2bmunLaS5AbW1iFqzas7GnS6KhCPISprTLR2Gd/9+DK6l9csN1Pr1PccK3GnN6VIfRa7B7tRz8ryElwKv9X96vcB0qZB/3OQPHQdpK0vVfTL2C3ZxneDkz0V6ozP5f7e0AvpGkKzxLbL6X/HPcpT4lf0J4US3WBc2XT70kGn5TQ0urIWT8dHa7rMssHtBUzol61ORjt+e4d5rEfbV45RSP3fnALtQO9i7Zv0X83IX9F8+880FeYRcIiNnDxKqwEzfzD75OV5Tduu8KAZACMmjkQ51BZ9ZSPrE5vGop22UVnhHN6OtrZiWxFV1VM3Lya/3nc5gCupms4CSdFpdIPjSLq9O+WfxnMKmFj6gI/NmA4gMVjCb2B9jHMIB3iZsyZs68V3mZhbBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
