travis:
  secure:
    BINSTAR_TOKEN: l3TYurBgJ9M6Ck78iwFzaelsm3rYetdXo8h02C9MbeKSN7uDrFTdij2oTJIKe3QRxqUOjq0QjySqyR+Dw4qeOn1q3ckRjmzJNGhfKVZPPMWv+0uwjZI8XAN/uRo+NGF5lBBcWJGk/Yz/I5zONPX4EpjfF8I0LYr+0R3/hLnPyKnluhsmMGGhap7ZCaSy66Z0pkFslusnOamuhc5jDb8fvBqMG0VrzltFtP/TAh7FBOJabaVVUc/1HD/jJ54Z68z48SJNLOTV1HRXYkEjzsyT6EPNkuBLoa58/Zh8EcuUh5wTrZ6InMyqEbiJ5oDfz+mn3rvkfUpot3YmCWGWuVMCWsYVWQQ4OrxBsHdc91UKow42iR16ezeSx34ctPIp+gzpDBknssQB0gOW7la9+ppAM6gBpwxz1Q7GIL7KNbjgwEIpueeveQoEC1U7er2CDZVQMcI0UDHspVDNmJIQ0mU/s8w95gSn0G57ZhjNkVfmcNep7PdhF0TAR92Y+QbsiQciymYLCq7C34bMzwEaRbtvaXOG7zayOJ9l4AbHDZ2IQ913FVK56GtwpnYqe4Q58bl9zXYCOAydTEDCuy0IfHnpiLszdmE99F6Yr4O11ub2abCOf4TM47HkruDr7hZh6dQkI81qngRPh4EZ/71m660IimFtWJv+06U76DfXY6hmm+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
